apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aia8gym3n-python
  janus-idp.io/tekton: aia8gym3n-python
  backstage.io/kubernetes-id: aia8gym3n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aia8gym3n-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
